# Read data

Import the data.
Data files are locally stored.

Import Aim 1: Exercise data

```{r}
L1 <- importDataToList("../data/raw/Ultragenyx Aim 1 Z score.xlsx")
L1[["file"]]
L1[["dim"]]
L1[["names"]]
L1[["head"]]
D1 <- L1[["data"]]
```

Import Aim 2: Diet data.
Metabolite `LCAC total` is the sum of `LC even AC total` and `LC odd AC total`; remove `LCAC total` data.

```{r}
L2 <- importDataToList("../data/raw/Ultragenyx Aim 2 Z score.xlsx")
L2[["file"]]
L2[["dim"]]
L2[["names"]]
L2[["head"]]
D2 <- L2[["data"]] %>% filter(metabolite != "LCAC total") %>% mutate(metabolite = droplevels(metabolite))
```


## Check data

Check the `value` and `logValue`.

```{r plotDataAim1, results = "asis", fig.height = 6, fig.width = 10}
kable(summarizeOutcome(D1))
ggplot(D1) +
  aes(x = logValue, y = metabolite, color = activity, fill = activity) +
  geom_jitter(alpha = 1/2) +
  facet_wrap(~ genotype) +
  scale_x_continuous("log10 scale") +
  scale_y_discrete("Metabolite") +
  scale_color_brewer("Activity", palette = "Set1") +
  scale_fill_brewer("Activity", palette = "Set1") +
  theme_bw()
ggsave("../figures/plotDataAim1.png", width = 10, height = 8, units = "in")
```

```{r plotDataAim2, results = "asis", fig.height = 6, fig.width = 10}
kable(summarizeOutcome(D2))
ggplot(D2) +
  aes(x = logValue, y = metabolite, color = chow, fill = chow) +
  geom_jitter(alpha = 1/2) +
  facet_wrap(~ genotype) +
  scale_x_continuous("log10 scale") +
  scale_y_discrete("Metabolite") +
  scale_color_brewer("Chow", palette = "Set1") +
  scale_fill_brewer("Chow", palette = "Set1") +
  theme_bw()
ggsave("../figures/plotDataAim2.png", width = 10, height = 8, units = "in")
```


Check fixed effects factors.

```{r}
D1 %>% group_by(genotype, activity) %>% tally
D1 %>% group_by(genotype, metabolite) %>% tally %>% print(n = nrow(.))
D1 %>% group_by(activity, metabolite) %>% tally %>% print(n = nrow(.))
```

```{r}
D2 %>% group_by(genotype, chow) %>% tally
D2 %>% group_by(genotype, metabolite) %>% tally %>% print(n = nrow(.))
D2 %>% group_by(chow, metabolite) %>% tally %>% print(n = nrow(.))
```
